version: '3'
services:
  q_and_a:
    container_name: q_and_a
    image: q_and_a
    ports:
      - "8080:8080"
    depends_on:
      - pgvector

  pgvector:
    container_name: pgvector
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      PGOPTIONS: maintenance_work_mem=512MB
    ports:
      - "5432:5432"
    volumes:
      - ./store/pgvector:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
